// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFfCWGwVncxMYD33BmFx8PalManYlNlDw',
    appId: '1:102289955166:web:b0ccde10d18c13a48a97cf',
    messagingSenderId: '102289955166',
    projectId: 'mobil-audio-app',
    authDomain: 'mobil-audio-app.firebaseapp.com',
    storageBucket: 'mobil-audio-app.firebasestorage.app',
    measurementId: 'G-ZETFCQSB1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl8ZVmbk6o2vBcGtjsGWpgi9Fgd2L9Mvc',
    appId: '1:102289955166:android:f834e97cf171627c8a97cf',
    messagingSenderId: '102289955166',
    projectId: 'mobil-audio-app',
    storageBucket: 'mobil-audio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6JDCixfdtywV8EX-jzH1Tm2DFVrpkIwM',
    appId: '1:102289955166:ios:b541118fe1e315b58a97cf',
    messagingSenderId: '102289955166',
    projectId: 'mobil-audio-app',
    storageBucket: 'mobil-audio-app.firebasestorage.app',
    iosBundleId: 'com.example.mobilAudioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6JDCixfdtywV8EX-jzH1Tm2DFVrpkIwM',
    appId: '1:102289955166:ios:b541118fe1e315b58a97cf',
    messagingSenderId: '102289955166',
    projectId: 'mobil-audio-app',
    storageBucket: 'mobil-audio-app.firebasestorage.app',
    iosBundleId: 'com.example.mobilAudioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFfCWGwVncxMYD33BmFx8PalManYlNlDw',
    appId: '1:102289955166:web:66912d7d37fecbbf8a97cf',
    messagingSenderId: '102289955166',
    projectId: 'mobil-audio-app',
    authDomain: 'mobil-audio-app.firebaseapp.com',
    storageBucket: 'mobil-audio-app.firebasestorage.app',
    measurementId: 'G-PW3QXGQJWW',
  );
}
